### ISSUE TITLE
What is the path stuff doing?

### ISSUE THREAD

**Issue by blakeembrey** [alex-ketch/metalsmith-renamer#1]
It's possible to use metalsmith without the path: https://github.com/alex-ketch/metalsmith-renamer/blob/master/lib/index.js#L16-L18. Why not just leave it alone? I could just add the permalinks stuff with adds the path property after I use the renamer.

**Comment by alex-ketch** [comment]
@blakeembrey Thanks for pointing that out, in my plugin sequence I had renamer running towards the bottom and forgot that `file.path` isn't there by default.
Your suggestion led me to clean it up quite a bit and just use the native path module instead.

Now renamer must be run before any path/permalink plugins to ensure they are set correctly.
