### ISSUE TITLE
Breaking change in 0.5.0 ?

### ISSUE THREAD

**Issue by dpobel** [alex-ketch/metalsmith-renamer#13]
0.5.0 breaks the build of my website while it has been working file with 0.4.1 and before without changes on my side. It seems like it's caused by the use of `export` instead of `module.exports`.

```js
var renamer = require('metalsmith-renamer'),

console.log(renamer);
```

gives different results. With 0.4.1

```
[Function: plugin]
```

While with 0.5.0:

```
{ default: [Function: renamer], renamer: [Function: renamer] }
```

**Comment by alex-ketch** [comment]
Hi @dpobel, seems like that was an unintended breakage during a refactor of this project.
Could you try with the latest release and let me know if you still have problems please?

`npm i -D metalsmith-renamer@latest` should install `v0.5.1` for you

**Comment by dpobel** [comment]
Hi @alex-ketch 

0.5.1 is working perfectly. Thank you!
